# Generated by Django 5.0.6 on 2024-08-26 10:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
        ('users', '0003_userinfos_userprofile_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=100, verbose_name='问题')),
                ('reply', models.CharField(max_length=300, verbose_name='回答')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('favs', models.PositiveIntegerField(default=0, verbose_name='收藏数')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name_plural': 'Data',
            },
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='题目')),
                ('content', models.TextField(max_length=4000, verbose_name='内容')),
                ('discussion_created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('views', models.PositiveIntegerField(default=0, editable=False, verbose_name='浏览次数')),
                ('likes', models.PositiveIntegerField(default=0, editable=False, verbose_name='喜欢')),
                ('replys', models.PositiveIntegerField(default=0, editable=False, verbose_name='回复数')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userinfos')),
            ],
            options={
                'verbose_name_plural': 'Discussion',
            },
        ),
        migrations.CreateModel(
            name='LikeNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.discussion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user',
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(default='', max_length=4000, verbose_name='回答')),
                ('rlikes', models.PositiveIntegerField(default=0, editable=False, verbose_name='回答喜欢数')),
                ('rfavs', models.PositiveIntegerField(default=0, editable=False, verbose_name='回答收藏数')),
                ('reply_created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('discussion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.discussion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userinfos')),
            ],
            options={
                'verbose_name_plural': 'Reply',
            },
        ),
        migrations.CreateModel(
            name='FavNum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.discussion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userinfos')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.reply')),
            ],
            options={
                'verbose_name_plural': 'Favorite Numbers',
            },
        ),
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discussion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.discussion')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.userinfos')),
                ('reply', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.reply')),
            ],
            options={
                'verbose_name_plural': 'Favorite',
            },
        ),
    ]
