# Generated by Django 5.0.6 on 2024-09-08 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_liked_users_post_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='链接标题')),
                ('url', models.URLField(verbose_name='链接地址')),
                ('description', models.TextField(blank=True, verbose_name='链接描述')),
            ],
        ),
    ]
